<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "catedra".
 *
 * @property integer $catedra_id
 * @property integer $carrera
 * @property integer $materia
 * @property string $nombre
 *
 * @property \app\modules\crud\models\Carrera $carrera0
 * @property \app\modules\crud\models\Materium $materia0
 * @property \app\modules\crud\models\Prg[] $prgs
 * @property string $aliasModel
 */
abstract class Catedra extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'catedra';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['carrera', 'materia', 'nombre'], 'required'],
            [['carrera', 'materia'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['carrera'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\Carrera::className(), 'targetAttribute' => ['carrera' => 'carrera_id']],
            [['materia'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\Materium::className(), 'targetAttribute' => ['materia' => 'materia_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'catedra_id' => Yii::t('models', 'Catedra ID'),
            'carrera' => Yii::t('models', 'Carrera'),
            'materia' => Yii::t('models', 'Materia'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrera0()
    {
        return $this->hasOne(\app\modules\crud\models\Carrera::className(), ['carrera_id' => 'carrera']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMateria0()
    {
        return $this->hasOne(\app\modules\crud\models\Materium::className(), ['materia_id' => 'materia']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrgs()
    {
        return $this->hasMany(\app\modules\crud\models\Prg::className(), ['catedra' => 'catedra_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\CatedraQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\CatedraQuery(get_called_class());
    }


}
