<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\modules\crud\models\base;

use Yii;

/**
 * This is the base-model class for table "materia".
 *
 * @property integer $materia_id
 * @property integer $carrera
 * @property string $nombre
 *
 * @property \app\modules\crud\models\Carrera $carrera0
 * @property \app\modules\crud\models\Catedra[] $catedras
 * @property \app\modules\crud\models\Prg[] $prgs
 * @property string $aliasModel
 */
abstract class Materium extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'materia';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['carrera', 'nombre'], 'required'],
            [['carrera'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['carrera'], 'exist', 'skipOnError' => true, 'targetClass' => \app\modules\crud\models\Carrera::className(), 'targetAttribute' => ['carrera' => 'carrera_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'materia_id' => Yii::t('models', 'Materia ID'),
            'carrera' => Yii::t('models', 'Carrera'),
            'nombre' => Yii::t('models', 'Nombre'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrera0()
    {
        return $this->hasOne(\app\modules\crud\models\Carrera::className(), ['carrera_id' => 'carrera']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCatedras()
    {
        return $this->hasMany(\app\modules\crud\models\Catedra::className(), ['materia' => 'materia_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrgs()
    {
        return $this->hasMany(\app\modules\crud\models\Prg::className(), ['materia' => 'materia_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\MateriumQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\MateriumQuery(get_called_class());
    }


}
