<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "carrera".
 *
 * @property integer $carrera_id
 * @property string $nombre
 *
 * @property \app\models\Catedra[] $catedras
 * @property \app\models\Materia[] $materias
 * @property \app\models\Prg[] $prgs
 * @property string $aliasModel
 */
abstract class Carrera extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'carrera';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre'], 'required'],
            [['nombre'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'carrera_id' => 'Carrera ID',
            'nombre' => 'Nombre',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCatedras()
    {
        return $this->hasMany(\app\models\Catedra::className(), ['carrera' => 'carrera_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMaterias()
    {
        return $this->hasMany(\app\models\Materia::className(), ['carrera' => 'carrera_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrgs()
    {
        return $this->hasMany(\app\models\Prg::className(), ['carrera' => 'carrera_id']);
    }




}
