<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "materia".
 *
 * @property integer $materia_id
 * @property integer $carrera
 * @property string $nombre
 *
 * @property \app\models\Carrera $carrera0
 * @property \app\models\Catedra[] $catedras
 * @property \app\models\Prg[] $prgs
 * @property string $aliasModel
 */
abstract class Materia extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'materia';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['carrera', 'nombre'], 'required'],
            [['carrera'], 'integer'],
            [['nombre'], 'string', 'max' => 100],
            [['carrera'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Carrera::className(), 'targetAttribute' => ['carrera' => 'carrera_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'materia_id' => 'Materia ID',
            'carrera' => 'Carrera',
            'nombre' => 'Nombre',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCarrera0()
    {
        return $this->hasOne(\app\models\Carrera::className(), ['carrera_id' => 'carrera']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCatedras()
    {
        return $this->hasMany(\app\models\Catedra::className(), ['materia' => 'materia_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrgs()
    {
        return $this->hasMany(\app\models\Prg::className(), ['materia' => 'materia_id']);
    }




}
