<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "plan".
 *
 * @property integer $plan_id
 * @property integer $carrera
 * @property string $nombre
 *
 * @property \app\models\Prg[] $prgs
 * @property string $aliasModel
 */
abstract class Plan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'plan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['carrera', 'nombre'], 'required'],
            [['carrera'], 'integer'],
            [['nombre'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'plan_id' => 'Plan ID',
            'carrera' => 'Carrera',
            'nombre' => 'Nombre',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPrgs()
    {
        return $this->hasMany(\app\models\Prg::className(), ['plan' => 'plan_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\PlanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\PlanQuery(get_called_class());
    }


}
