<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Prg $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Programas');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models.plural', 'Prg'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->prg_id, 'url' => ['view', 'prg_id' => $model->prg_id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud prg-view">

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <h1>
        <?= Html::encode($model->prg_id) ?>
        <small>
            <?= Yii::t('models', 'Programa') ?>
        </small>
    </h1>


    <div class="clearfix crud-navigation">

        <!-- menu buttons -->
        <div class='pull-left'>
            <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
            [ 'update', 'prg_id' => $model->prg_id],
            ['class' => 'btn btn-info'])
          ?>

            <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-copy"></span> ' . 'Copy',
            ['create', 'prg_id' => $model->prg_id, 'Prg'=>$copyParams],
            ['class' => 'btn btn-success'])
          ?>

            <?php 
 echo Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'New',
            ['create'],
            ['class' => 'btn btn-success'])
          ?>
        </div>

        <div class="pull-right">
            <?= Html::a('<span class="glyphicon glyphicon-list"></span> '
            . 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
        </div>

    </div>

    <hr/>

    <?php $this->beginBlock('app\models\Prg'); ?>

    
    <?php 
 echo DetailView::widget([
    'model' => $model,
    'attributes' => [
    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'carrera',
    'value' => ($model->carrera0 ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['carrera/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->carrera0->nombre, ['carrera/view', 'carrera_id' => $model->carrera0->carrera_id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Prg'=>['carrera' => $model->carrera]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'materia',
    'value' => ($model->materia0 ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['materia/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->materia0->nombre, ['materia/view', 'materia_id' => $model->materia0->materia_id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Prg'=>['materia' => $model->materia]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'catedra',
    'value' => ($model->catedra0 ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['catedra/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->catedra0->nombre, ['catedra/view', 'catedra_id' => $model->catedra0->catedra_id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Prg'=>['catedra' => $model->catedra]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'plan',
    'value' => ($model->plan0 ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['plan/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->plan0->nombre, ['plan/view', 'plan_id' => $model->plan0->plan_id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Prg'=>['plan' => $model->plan]])
        : 
        '<span class="label label-warning">?</span>'),
],
        'vale_desde',
        'vale_hasta',
        'archivo',
        'activo',
    ],
    ]);
  ?>

    
    <hr/>

    <?php 
 echo Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'prg_id' => $model->prg_id],
    [
    'class' => 'btn btn-danger',
    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
    'data-method' => 'post',
    ]);
  ?>
    <?php $this->endBlock(); ?>


    
    <?php 
        echo Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [
 [
    'label'   => '<b class=""># '.Html::encode($model->prg_id).'</b>',
    'content' => $this->blocks['app\models\Prg'],
    'active'  => true,
],
 ]
                 ]
    );
    ?>
</div>
